# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello <- function() {
    .Call('_hellorust_hello', PACKAGE = 'hellorust')
}

random_number <- function() {
    .Call('_hellorust_random_number', PACKAGE = 'hellorust')
}

run_threads <- function() {
    invisible(.Call('_hellorust_run_threads', PACKAGE = 'hellorust'))
}

