# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_wrapper <- function() {
    .Call('_hellorust_hello_wrapper', PACKAGE = 'hellorust')
}

random_wrapper <- function() {
    .Call('_hellorust_random_wrapper', PACKAGE = 'hellorust')
}

threads_wapper <- function() {
    invisible(.Call('_hellorust_threads_wapper', PACKAGE = 'hellorust'))
}

